export const home = {
    greet: "Hi, I am Abhinav Gupta",
    description: "I am a software engineer, developing applications with a wide variety\
    of tools e.g. java, javascript (typescript), python, c++, spring, react, angular\
    etc. My interest lies in backend development, machine learning and bits of frontend\
    development. I can adapt to new set of tools for developing applications rapidly. \
    I am set out to bring a change in the world with my skills.",
    projects: {
        title: "Projects",
        infoTitleLgScreen: "Click on the projects to know more",
        infoTitleSmScreen: "Tap on the projects to know more",
        projectsArray: [
            {
                title: "Image captioning System",
                description: "The system consists of a deep learning models \
                that generates the cpation of the input image, it consists \
                of a LSTM trained on the feature vector generated by VGG-16 \
                model on the imput images.",
                link: "https://www.kaggle.com/abhinav99ash29/image-captioning-system-with-beam-search"
            },
            {
                title: "Real-time control of FSW Process",
                description: "The project consisted of the implemetation of a \
                system for real-time monitoring and control of the Friction \
                Stir Welding process using socket programming, machine \
                learning and cloud computing",
                link: "https://doi.org/10.1016/j.cirpj.2020.03.004"
            },
            {
                title: "Video Conferencing application in python",
                description: "The application uses openCV to acquire frames \
                and socket programming for transferring video and audio \
                data between various clients.",
                link: "https://github.com/abhinav99ash29/Chatroom"
            },
            {
                title: "Speech recognition using LPC",
                description: "The project consisted of a speech controlled \
                bot using the LPC features and mahalonobis distance \
                matching between the predicted and actual features \
                for determining the label of the speech sample.",
                link: "https://github.com/abhinav99ash29/Speech-Recognition-LPC"
            }
        ]
    }
};

export const about = {
    aboutText: "I am a software developer with interest in machine \
    learning and robotics, I keep experimenting, building stuff \
    and working on side projects. I like science fiction, deep \
    space talks, watching animes, reading mangas, watching \
    movies, exploring new technology, learning new things, \
    I like playing volleyball and I watch a whole lot of TED \
    in my free time. I don't really have a hobby as such. \
    I am a static explorer and a nerd."
};

export const contact = {
    reachText: "Please reach out to me at:",
    email: "abhinav.gupta.tech [at] gmail [dot] com",
    orText: "Or you can message me from below (feature will be available soon)"
};